[package]
name = "hello_world"
version = "0.0.1"
authors = ["Alexander 'Theliraan' Lazarev <theliraan@gmail.com>"]
edition = "2021" # allows to use dependencies like this

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"