[package]
name = "hello_world"
version = "0.0.1"
authors = ["Alexander 'Theliraan' Lazarev <theliraan@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
